name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Docker registry login
        if: ${{github.ref == 'refs/heads/main'}}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Publish
        uses: renovatebot/internal-tools@62f963cfc98faa26ad8b68e64902b04882619a83 # renovate: tag=v1.10.2
        with:
          command: docker-builder
          dry-run: ${{ github.ref != 'refs/heads/main' }}
          last-only: true
          major-minor: false
